version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: super
      POSTGRES_PASSWORD: mercado
      POSTGRES_DB: mercadinho
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://super:mercado@db/mercadinho

volumes:
  postgres-data: